### ISSUE TITLE
Issue with "PoolRooms" interior

### ISSUE THREAD

**Issue by Canatopher** [Drako1245/LiminalPoolRoomsLC#1]
Having the "LiminalPools" interior mod enabled causes all the shallow water in the PoolRooms interior to act like regular water that prevents sprinting, prevents stamina regeneration, and slows down the player. When disabling the LiminalPools interior the water within PoolRooms acts as it did before - not restricting your ability to sprint and move.

It is likely that this interior mod is messing with water in general, and thus may have an impact on other shallow bodies of water that aren't supposed to apply stamina restricting properties.

https://thunderstore.io/c/lethal-company/p/skidz/PoolRooms/

**Comment by Drako1245** [comment]
Thanks for letting me know, I'll look into passing a few extra null checks to make sure it stop doing that
