### ISSUE TITLE
Water Audio is a bit quiet?

### ISSUE THREAD

**Issue by RosinRush** [Drako1245/LiminalPoolRoomsLC#2]
It doesn't feel "sloshy" if that makes sense? wading through it, the sound is nice, but for jumping in it feels odd. 

More an observation than anything else.

**Comment by Drako1245** [comment]
Hi RosinRush!
The water audio being quiet is a creative choice I made while working out the kinks in the water. It seemed that the noise the water made was obtrusively loud and needed to be turned down a bit. That being said, I will test a few different audio levels and make sure that the current level is/n't the best audio for it and adjust as needed.

Thank you,
Drako

**Comment by RosinRush** [comment]
Sounds good!

**Comment by Drako1245** [comment]
Fixed on release of v1.0.7
