### ISSUE TITLE
Stay alive in the water pit

### ISSUE THREAD

**Issue by Xeraccoon** [Drako1245/LiminalPoolRoomsLC#3]
some pits in the game are made so that we cannot go back up, it would have to kill, because with the oxygen mod, we stay in the water hole for a long time before dying of asphyxiation

**Comment by Drako1245** [comment]
I'll look into a specific fix for this, but adding kill triggers ruins the multiplayer magic of hearing the splash and sounds of your friends at the bottom of the water panicking. My thoughts on flippers and oxygen were that if you have the mod that would allow you to escape water / survive longer in water, my water shouldn't function any differently, but I suppose with no way out it just stalls the game.

**Comment by Xeraccoon** [comment]
This is actually funny, we could hear a friend blocking underwater, but the time it takes people to die is too long with the "oxygen" mod and even longer if you are alone in the hole and no one know where you are, unfortunately there is no mod that allows you to swim, or to be able to chain jump into the water to be able to go back up

**Comment by Xeraccoon** [comment]
and it is mandatory to have a ground in the pit to retain water ? because the map arcadia has a water pit with a hole and if we fall in it we are dead

**Comment by Drako1245** [comment]
Added configuration options to enable kill triggers in the pits

**Comment by Xeraccoon** [comment]
Perfect :)
