### ISSUE TITLE
[bug] AP grabInvalidated: False.

### ISSUE THREAD

**Issue by DravenXD** [Drako1245/LiminalPoolRoomsLC#6]
Picking up a second custom apparatus (AP) item causes the players inventory to bug out, appearing to fill up two inventory slots. The apparatus cannot be dropped in this state. The player character cannot interact with doors or other nodes which can regularly be interacted with while in this state. During this state, the Bepinex log continuously throws the following info: grabInvalidated: False.
![Lethal Company Screenshot 2024 10 14 - 20 01 53 06](https://github.com/user-attachments/assets/89193d95-af21-4471-815c-6d04216ff47e)
![bug](https://github.com/user-attachments/assets/1530f328-48f6-4b05-86ef-0836c4dd5fff)

**Comment by DravenXD** [comment]
I forgot to add, this bug will not be fixed unless the user restarts the game. The bug is persistent through the main menu. So soft reloading a save is not an option (even if the first AP you collected is lost, or was not saved), the entire game must be re-launched.
Edit: To clarify, picking up a second AP, even after soft-reloading, causes the bug to happen. If the player chooses never to pick one up after soft-reload, they should, in theory, be fine.

**Comment by Drako1245** [comment]
Hi Draven,
Can you please send your modpack and elaborate on what you mean by "a second custom apparatus"?

**Comment by DravenXD** [comment]
Hello Drako.
Edit: I'm going to re-write this message for readability.
-"a second custom apparatus" implies that a custom AP from this mod had already been collected before.
-To clarify some of my other posts: The bug still happens if you collect a first custom AP, save/reload (causing it to get deleted), and then pick up another custom AP. It seems to somehow persist on the save file that an initial custom AP had been collected, even if the initial AP had been deleted by reloading the save. Saving and reloading multiple times seems to have no effect on internally resetting the games "knowledge" of a first AP item having been collected.
-The bug first happened on the custom moon Argent by Tolian with Liminal Pools as the interior. 
-My current modpack has the interior set to appear exclusively on Halation by DemonMae.
-Edit2: I have not attempted collection of the custom AP since this happened because I'm worried it might've corrupted my previous save file.
-Edit4: Other modded items work as intended (Halatian adds a florescent tube, MAO school adds lots of stuff, all of these behave as expected). 
0192bb57-829b-a4e8-c66c-16de4b52a201

Edit3: Please note that v65 just dropped, so there may be problems with other mods in my pack that were not present in v64.

**Comment by LoafOrc** [comment]
This also breaks FacilityMeltdown due to (i assume) a prefix patch failing which fails to set isLungDocked.

edit: probably should have included the exception lol
```
[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Component.GetComponent[T] () (at <e27997765c1848b09d8073e5d642717a>:IL_0021)
PooluginRooms.AppEventListener.StartAnim (LungProp __instance) (at <7fca95fde5424d569475f096f36f1955>:IL_0001)
LethalLevelLoader.ExtendedEvent`1[T].Invoke (T param) (at ./General/EventPatches.cs:295)
LethalLevelLoader.EventPatches.LungPropEquipItem_Prefix (LungProp __instance) (at ./General/EventPatches.cs:264)
(wrapper dynamic-method) LungProp.DMD<LungProp::EquipItem>(LungProp)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::SwitchToItemSlot>(GameNetcodeStuff.PlayerControllerB,int,GrabbableObject)
```

**Comment by Drako1245** [comment]
Fixed
